# This workflow will install Python dependencies, run unit_tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SIMPA tests

on:
  # run SIMPA tests on pushes to the main or develop branch
  push:
    branches: [ main, develop ]
  # and on all pull requests to the main or develop branch
  pull_request:
    branches: [ main, develop ]
  # as well as upon manual triggers through the 'Actions' tab of the GitHub UI
  workflow_dispatch:
  # Additionally, run Friday morning 6AM, so that we can react quickly if things break
  schedule:
  - cron: "0 5 * * 5"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install simpa
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Testing
      run: |
        python simpa_tests/do_coverage.py
        coverage xml
